### ISSUE TITLE
Password not copied properly on initial clone.

### ISSUE THREAD

**Issue by rdetwiler** [versionpress/versionpress#1107]
Hello,
Was testing a typical clone creation today, and got a WordPress connection error on stage. Seems that when copying the password over it stripped the _**$3** symbols in the password:

```
Directory 'staging' already exists, it will be deleted before cloning. Proceed? [y/n] y
Success: Site files cloned
Success: Clone added as a remote
Success: Enabled pushing to the original repository
Success: Enabled pushing to the clone
Success: wp-config.php updated
Success: Copied VersionPress
Warning: mysqli_real_connect(): (HY000/1045): Access denied for user '******'@'localhost' (using password: YES) in /home/********/staging/wp-includes/wp-db.php on line 1501
...
Success: All done. Clone created here:

Path:   /home/********/staging
URL:    http://staging.**********.com
```

Checking the DB_PASSWORD from prod to stage, I see _**$3** were stripped:
Prod:
define('DB_PASSWORD', 'Ns$ou!_$3Tip');
Stage:
define('DB_PASSWORD', 'Ns$ou!_Tip');

Info:

```
WP 4.6
PHP binary:     /opt/alt/php56/usr/bin/php
PHP version:    5.6.24
php.ini used:   /opt/alt/php56/etc/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI version: 0.24.1
VersionPress 3.0.2
```

Any ideas on a fix for this?
Thanks!

**Comment by JanVoracek** [comment]
Hi, thanks for the report. 
It looks like the `$3` is evaluated as a variable. You can try to find the bug in the `wp vp clone` command (in [`src/Cli/vp.php`](https://github.com/versionpress/versionpress/blob/469fe08b4506166d879fff52a09f48b4953ce391/plugins/versionpress/src/Cli/vp.php#L400)) and send a pull request if you are brave enough :) Otherwise, we will look on it later (but it will be definitely part of the 4.0 release).
