### ISSUE TITLE
Plugin definition discovery: local location outside of <plugin>/.versionpress

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1176]
https://github.com/versionpress/versionpress/issues/1036 implements a discovery method that expects plugin definition files (`schema.yml`, `actions.yml` etc.) to be located at `<some-plugin>/.versionpress`. There should also be an external location from where the definitions could be loaded, two initial candidates being:

```
wp-content/plugins/.versionpress
wp-content/vpdb/.versionpress (or some other folder name)
```

I like the `plugins` folder better because not everything in a plugin definition is tied to a DB and `vpdb` is very database-specific.

Inside it, it would probably just be directories for plugins so the complete example would look like:

```
wp-content/plugins/.versionpress
    akismet/
        schema.yml
        actions.yml
    woocommerce/
        schema.yml
        actions.yml
    ...
```

After this is implemented, there will be an online repo of these definitions, sort of like DefinitelyTyped for TypeScript. VersionPress will be downloading plugin definitions from that repo to this local structure. See https://github.com/versionpress/versionpress/issues/1243.

---

🏁 PR https://github.com/versionpress/versionpress/pull/1246

**Comment by unclhos** [comment]
Also need to determine how to deal with plugin versions and force rediscovery of plugins that already have definitions downloaded. Ideally this would happen during the plugin upgrade hook, but if new definitions aren't ready, should be able to force it some way (CLI with eventual GUI).

**Comment by pavelevap** [comment]
Yes, subdirectory `/.versionpress` is currently not very friendly and my definition files are deleted everytime when plugin is updated automatically :-)

I would suggest `wp-content/.versionpress/` because there will be also definition files for themes (see #1164) and not only plugins. So, we can have `wp-content/.versionpress/plugins` and `wp-content/.versionpress/themes`. And also `wp-content/plugins` is default WP directory, maybe some conflicts may appear?

As regards versioning, maybe we could take inspiration from WP language packs and their API (it looks like similar feature = languages for plugins and themes)? There are no versions but only date of modified files.

**Comment by borekb** [comment]
@unclhos Note that this issue is _not_ about the online plugin repo, that will be dealt with in a separate issue. But point taken.

**Comment by borekb** [comment]
@pavelevap Do you know if a slug is unique across plugins and themes on wordpress.org? In other words, can there be `https://wordpress.org/plugins/example/` and `https://wordpress.org/themes/example/` at the same time? That would influence the decision somewhat.
