### ISSUE TITLE
Use MkDocs for docs.versionpress.net

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1332]
[Our docs](https://docs.versionpress.net/en) are currently powered by [versionpress/docs-site](https://github.com/versionpress/docs-site), a small Node.js app that serves a bunch of Markdown files – currently the contents of [`/docs/content`](https://github.com/versionpress/versionpress/tree/2071052ad33a782e96ca206ccca6891e52bc614f/docs/content) folder in this repo. The idea was that we'd be able to switch versions of the documentation and language versions but the reality is that these features are not used and static site generation would be much simpler.

Specifically, [MkDocs](http://www.mkdocs.org/) + [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) is a nice combo that we already use for our [".com" docs](https://docs.versionpress.com/) and would also provide all we really need for ".net" docs:

- Markdown source files
- Search
- Navigation: menu & prev/next
- Design options

If someone wanted to take this, it would be great. What should happen as part of the PR:

- [ ] Update the Markdown files and their structure for MkDocs
- [ ] Move the release notes to GitHub releases and/or `CHANGELOG.md`
- [ ] Ideally keep the design. I quite like the distinct, although relatively old-school [looks of our docs](https://user-images.githubusercontent.com/101152/40269203-2f5d4c2a-5b7b-11e8-9ea0-5ca338689e0c.png).
- [ ] Update README / deployment instructions

Related: https://github.com/versionpress/docs-site/issues/92

**Comment by lisaross** [comment]
Looking into this now - mkdocs has some differences in the way it handles navigation:

1. auto directory traversing creates exact filenames in the nav, which is faster, but it's messy: 
http://drops.lisaross.tech/X0REk4 (note the content/language nav items)

2. we can use a more manual nav setup in the config using [named pairs](https://mkdocs.readthedocs.io/en/stable/user-guide/configuration/#pages). 
That's better: http://drops.lisaross.tech/8ut4ik

I recommend using option 2 and maintaining the config for the navigation from a usability perspective. Yes, that's another step for doc maintainers, but since mkdocs is so fast otherwise I think it's worth it. There might be a middle-ground compromise where we remove content/en and name files with caps, but I still think the config gives more flexibility (have same file in multiple locations in nav, change nav without changing file name, etc) and is more forward friendly.

I also thought it might be a good time to rename some pages and remove numbers before filenames to clean it up, recognizing we'd also have to set up redirects for historical links - is that something you would be open to? Or better for you to leave structure/pages as-is? I tend to like to refactor and fix when given the opportunity, but if you have reason for the numbering that weighs higher, let me know.

I've pulled in the material theme like you're using on the .com while getting structure sorted - will have a look at the theme used on current .net to see if I can recreate when I've got content flowing. That said, the material theme is clean and you might decide you want to keep it.

Question - where are you hosting the docs when done?

**Comment by borekb** [comment]
@lisaross Thanks for looking into this!

I'm also for option 2, that's what we use for <https://docs.versionpress.com> and it's working fine.

Regarding numbers in filenames, they are there only to guarantee menu order. For example, `docs/content/en/01-getting-started/10-using-versionpress` renders as `docs.versionpress.net/en/getting-started/using-versionpress` so we can safely get rid of them.

About the design: I agree that material theme is super-slick, and I generally like it. At the same time, there is enough confusion about VersionPress vs. VersionPress.com so I think the docs should stay distinctly different. The current theme is basically GitHub's rendering of Markdown plus some custom things like header, sidebar and footer.

docs.versionpress.net are hosted on VersionPress.com right now, in a Docker container. When it's a statically generated site, it can be hosted anywhere, even GitHub pages now that they support [HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

**Comment by borekb** [comment]
All is now done, I've updated the issue description and published a [blog post](https://blog.versionpress.net/2018/06/updated-docs-site/) on this. It was a pleasure to collaborate on this, @lisaross; hope you had a good time as well!
