### ISSUE TITLE
4.0-beta ZIP is broken

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1365]
Similar to _Unable to unzip 4.0-alpha1_ #1138 and probably already reported in https://github.com/versionpress/support/issues/121, I'm not able to extract the ZIP on macOS.

**Comment by toshotosho** [comment]
FWIW, versionpress-4.0-beta.zip downloaded from the releases page moments ago worked fine for me both on Mac and Windows 10.

**Comment by borekb** [comment]
Interesting, I'm getting this in Finder:

<img width="490" alt="screenshot 2019-01-07 at 16 53 19" src="https://user-images.githubusercontent.com/101152/50777778-cae95c00-129c-11e9-9ff6-09096982cddc.png">

**Comment by Ishirak** [comment]
Uploading the zip directly to WordPress works correctly, however, as you both stated, there are issues when trying to directly unzip the file.

Since the last time we published the last beta version we've singificantly changed our publishing process and we're now using a different tool to compress our plugin. However, if you like to use the exact copy of the last beta version, you can download it here. It should be fixed.

[versionpress-4.0-beta.zip](https://github.com/versionpress/versionpress/files/2736150/versionpress-4.0-beta.zip)

**Comment by borekb** [comment]
Thanks, @Ishirak, I've uploaded the ZIP [to releases](https://github.com/versionpress/versionpress/releases/tag/4.0-beta) and also added a fresher build, [`versionpress-4.0-beta-177-gf208351.zip`](https://github.com/versionpress/versionpress/releases/download/4.0-beta/versionpress-4.0-beta-177-gf208351.zip), there.

**Comment by candrews** [comment]
@borekb instead of adding a new release (4.0-beta-177-gf208351) to the existing release (4.0-beta), can you please create a new release for the new release? :)
