### ISSUE TITLE
Environment name causes invalid and annoying code line in frontend

### ISSUE THREAD

**Issue by trebitzki** [versionpress/versionpress#1407]
Using version 4.0-beta-177-gf208351. Set environment name to dev. After activation the line "define('VP_ENVIRONMENT', 'dev');" is injected at the top of the page html, backend and frontend, on twentynineteen quite big for visitors. Deactivation didn't help, had to uninstall.

I assume the line is supposed to be PHP. You should fix that.

**Comment by borekb** [comment]
Hi @trebitzki, this sounds like a misconfiguration to me (PHP not being processed by a web server?), could you please open a new issue in the [support repo](https://github.com/versionpress/support) if you still need help? Thank you.

**Comment by trebitzki** [comment]
@borekb: not a configuration issue. If PHP were not processed Wordpress would bork out!

![Screen Shot 2019-03-27 at 15 20 27](https://user-images.githubusercontent.com/940634/55084997-2f4ed700-50a6-11e9-9ad6-312be9a4abb8.png)

**Comment by trebitzki** [comment]
BTW you seem to be a bit fast on the Closed trigger. I would have answered your question within a few minutes. Should I really open a new ticket?

**Comment by borekb** [comment]
Leaking PHP code to frontend is most likely a configuration issue, not a bug in VersionPress' code itself as that would be reported many times already. So my instinct is that this is most likely a support issue, for which we have a separate repo. That's why I closed this – it's just housekeeping, not a lack of patience :) Sorry if this was confusing.
