### ISSUE TITLE
WP-CLI implementation for remaining Selenium tests

### ISSUE THREAD

**Issue by jameskraus** [versionpress/versionpress#967]
Currently, even if the e2e test type is set to wp-cli, the run-tests task installs selenium every time the tests are run. The run-tests feature could be much faster if this was not the case. 

The relevant configuration is in the test-config.yml:

```
# Type of workers that will run the tests (selenium / wp-cli)
end2end-test-type: wp-cli
```

**Comment by JanVoracek** [comment]
VersionPress has also some [Selenium-only tests](https://github.com/versionpress/versionpress/tree/39c5a9cdd24a00fda0c9bac10f22634d4a4e27b3/plugins/versionpress/tests/Selenium). `gulp run-tests` run them all.

Maybe we could rewrite them in the future.

**Comment by borekb** [comment]
Changed title from what sounded like a bug (which it was not) to an actual improvement. It will be great to have a possibility to run the whole test suite on WP-CLI only.

**Comment by jameskraus** [comment]
Closing, no longer working on this. Feel free to open this if it's important to you.

**Comment by borekb** [comment]
I was just looking at this issue yesterday as part of the recent testing effort (#1389) and was wondering what it was about. I realized that the title change that I made in April 2016 was wrong – I then misunderstood what you reported.

I'm reverting the title back and indeed, this issue is no longer relevant as Selenium tests are disabled. We plan to re-enable them in #1402.
