### ISSUE TITLE
"[VP]" added to commits done via wp-admin

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#971]
Not entirely sure if this is a bug but it seems weird to me that a manual commit via Git CLI would be just "Updated template" while a commit via VersionPress screen in wp-admin creates "[VP] Updated template":

![image](https://cloud.githubusercontent.com/assets/101152/14761823/04f5200c-096b-11e6-86d7-429fc8889df6.png)

**Comment by JanVoracek** [comment]
The problem is that we use `UntrackedChangeInfo` for manual commits and `GitRepository` adds prefix `[VP] ` to all commit messages. But when parsing commits, VersionPress use plain commit message for `UntrackedChangeInfo` – because it was originally used only for true manual commits done from CLI.

I suggest not to use `UntrackedChangeInfo` for manual commits from our GUI. The question is how to name the new `ChangeInfo`. Or maybe we could use `VersionPressChange` with action `versionpress/commit`?

**Comment by borekb** [comment]
My opinion is that `GitRepository` should not be adding `[VP]` to all commits – it's probably a historic thing because in the past, all commits created by VersionPress were automatically `TrackedChangeInfo`s (results of _automatic_ change tracking, had the `VP-Action` tag etc.). That is no longer true as new commits can be created via wp-admin and although they are slightly richer than plain commits created via Git CLI (they have an `X-VP-Environment` tag etc.), they are still manual and I think that the `[VP]` prefix should only denote commits created by VersionPress _automatically_.

**Comment by JanVoracek** [comment]
The "UI level" is fixed by #1009. VersionPress GUI doesn't display the prefix but the commit still has it.

**Comment by borekb** [comment]
Moving this to 4.0 where there will be enough time to consider this properly.

**Comment by borekb** [comment]
- UI is fixed by #1009 
- Whether to add `[VP]` prefix will be decided with #979 so this one can be closed.
